
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Llave_cierre = 32;
  public static final int Llave_apertura = 31;
  public static final int True = 50;
  public static final int Coma = 47;
  public static final int Parentesis_apertura = 29;
  public static final int Null = 10;
  public static final int If = 11;
  public static final int Op_Logico = 40;
  public static final int Potencia = 28;
  public static final int Default = 17;
  public static final int Simb_especial = 49;
  public static final int Numeral = 21;
  public static final int Else = 12;
  public static final int Break = 48;
  public static final int Read = 18;
  public static final int Op_Incremento = 37;
  public static final int Op_Relacional = 39;
  public static final int Punto = 46;
  public static final int Op_Decremento = 38;
  public static final int Return = 19;
  public static final int While = 13;
  public static final int Division = 25;
  public static final int Int = 2;
  public static final int Float = 3;
  public static final int Modulo = 27;
  public static final int String_literal = 8;
  public static final int Corchete_cierre = 34;
  public static final int Corchete_apertura = 33;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Switch = 14;
  public static final int False = 51;
  public static final int Op_Booleano = 41;
  public static final int Linea = 44;
  public static final int Parentesis_cierre = 30;
  public static final int Comilla_simple = 36;
  public static final int Char = 5;
  public static final int Print = 16;
  public static final int ERROR = 45;
  public static final int Case = 15;
  public static final int String = 7;
  public static final int Identificador = 42;
  public static final int Resta = 24;
  public static final int Char_literal = 6;
  public static final int Bool = 4;
  public static final int Array = 9;
  public static final int Multiplicacion = 26;
  public static final int Numero = 43;
  public static final int Suma = 23;
  public static final int Main = 20;
  public static final int Igual = 22;
  public static final int Comillas = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Int",
  "Float",
  "Bool",
  "Char",
  "Char_literal",
  "String",
  "String_literal",
  "Array",
  "Null",
  "If",
  "Else",
  "While",
  "Switch",
  "Case",
  "Print",
  "Default",
  "Read",
  "Return",
  "Main",
  "Numeral",
  "Igual",
  "Suma",
  "Resta",
  "Division",
  "Multiplicacion",
  "Modulo",
  "Potencia",
  "Parentesis_apertura",
  "Parentesis_cierre",
  "Llave_apertura",
  "Llave_cierre",
  "Corchete_apertura",
  "Corchete_cierre",
  "Comillas",
  "Comilla_simple",
  "Op_Incremento",
  "Op_Decremento",
  "Op_Relacional",
  "Op_Logico",
  "Op_Booleano",
  "Identificador",
  "Numero",
  "Linea",
  "ERROR",
  "Punto",
  "Coma",
  "Break",
  "Simb_especial",
  "True",
  "False"
  };
}

